export default {
    GET_START_WARS_LIST: 'DASHBOARD/GET_START_WARS_LIST',
    GET_START_WARS_LIST_SUCCESS: 'DASHBOARD/GET_START_WARS_LIST_SUCCESS',
    GET_START_WARS_LIST_ERROR: 'DASHBOARD/GET_START_WARS_LIST_ERROR',

    GET_STAR_WARS_DETAILS: 'DASHBOARD/GET_STAR_WARS_DETAILS',
    GET_STAR_WARS_DETAILS_SUCCESS: 'DASHBOARD/GET_STAR_WARS_DETAILS_SUCCESS',
    GET_STAR_WARS_DETAILS_ERROR: 'DASHBOARD/GET_STAR_WARS_DETAILS_ERROR',
}